/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyWishesRouteImport } from './routes/journey.wishes'
import { Route as JourneyPasswordRouteImport } from './routes/journey.password'
import { Route as JourneyNightRouteImport } from './routes/journey.night'
import { Route as JourneyMusicRouteImport } from './routes/journey.music'
import { Route as JourneyMemoriesRouteImport } from './routes/journey.memories'
import { Route as JourneyLoadingRouteImport } from './routes/journey.loading'
import { Route as JourneyLetterRouteImport } from './routes/journey.letter'
import { Route as JourneyGiftRouteImport } from './routes/journey.gift'
import { Route as JourneyFinalRouteImport } from './routes/journey.final'
import { Route as JourneyEnvelopeRouteImport } from './routes/journey.envelope'
import { Route as JourneyCreditsRouteImport } from './routes/journey.credits'
import { Route as JourneyCakeRouteImport } from './routes/journey.cake'

const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyWishesRoute = JourneyWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyPasswordRoute = JourneyPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyNightRoute = JourneyNightRouteImport.update({
  id: '/night',
  path: '/night',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyMusicRoute = JourneyMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyMemoriesRoute = JourneyMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyLoadingRoute = JourneyLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyLetterRoute = JourneyLetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyGiftRoute = JourneyGiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyFinalRoute = JourneyFinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyEnvelopeRoute = JourneyEnvelopeRouteImport.update({
  id: '/envelope',
  path: '/envelope',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyCreditsRoute = JourneyCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyCakeRoute = JourneyCakeRouteImport.update({
  id: '/cake',
  path: '/cake',
  getParentRoute: () => JourneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRouteWithChildren
  '/journey/cake': typeof JourneyCakeRoute
  '/journey/credits': typeof JourneyCreditsRoute
  '/journey/envelope': typeof JourneyEnvelopeRoute
  '/journey/final': typeof JourneyFinalRoute
  '/journey/gift': typeof JourneyGiftRoute
  '/journey/letter': typeof JourneyLetterRoute
  '/journey/loading': typeof JourneyLoadingRoute
  '/journey/memories': typeof JourneyMemoriesRoute
  '/journey/music': typeof JourneyMusicRoute
  '/journey/night': typeof JourneyNightRoute
  '/journey/password': typeof JourneyPasswordRoute
  '/journey/wishes': typeof JourneyWishesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRouteWithChildren
  '/journey/cake': typeof JourneyCakeRoute
  '/journey/credits': typeof JourneyCreditsRoute
  '/journey/envelope': typeof JourneyEnvelopeRoute
  '/journey/final': typeof JourneyFinalRoute
  '/journey/gift': typeof JourneyGiftRoute
  '/journey/letter': typeof JourneyLetterRoute
  '/journey/loading': typeof JourneyLoadingRoute
  '/journey/memories': typeof JourneyMemoriesRoute
  '/journey/music': typeof JourneyMusicRoute
  '/journey/night': typeof JourneyNightRoute
  '/journey/password': typeof JourneyPasswordRoute
  '/journey/wishes': typeof JourneyWishesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journey': typeof JourneyRouteWithChildren
  '/journey/cake': typeof JourneyCakeRoute
  '/journey/credits': typeof JourneyCreditsRoute
  '/journey/envelope': typeof JourneyEnvelopeRoute
  '/journey/final': typeof JourneyFinalRoute
  '/journey/gift': typeof JourneyGiftRoute
  '/journey/letter': typeof JourneyLetterRoute
  '/journey/loading': typeof JourneyLoadingRoute
  '/journey/memories': typeof JourneyMemoriesRoute
  '/journey/music': typeof JourneyMusicRoute
  '/journey/night': typeof JourneyNightRoute
  '/journey/password': typeof JourneyPasswordRoute
  '/journey/wishes': typeof JourneyWishesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journey'
    | '/journey/cake'
    | '/journey/credits'
    | '/journey/envelope'
    | '/journey/final'
    | '/journey/gift'
    | '/journey/letter'
    | '/journey/loading'
    | '/journey/memories'
    | '/journey/music'
    | '/journey/night'
    | '/journey/password'
    | '/journey/wishes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journey'
    | '/journey/cake'
    | '/journey/credits'
    | '/journey/envelope'
    | '/journey/final'
    | '/journey/gift'
    | '/journey/letter'
    | '/journey/loading'
    | '/journey/memories'
    | '/journey/music'
    | '/journey/night'
    | '/journey/password'
    | '/journey/wishes'
  id:
    | '__root__'
    | '/'
    | '/journey'
    | '/journey/cake'
    | '/journey/credits'
    | '/journey/envelope'
    | '/journey/final'
    | '/journey/gift'
    | '/journey/letter'
    | '/journey/loading'
    | '/journey/memories'
    | '/journey/music'
    | '/journey/night'
    | '/journey/password'
    | '/journey/wishes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JourneyRoute: typeof JourneyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/wishes': {
      id: '/journey/wishes'
      path: '/wishes'
      fullPath: '/journey/wishes'
      preLoaderRoute: typeof JourneyWishesRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/password': {
      id: '/journey/password'
      path: '/password'
      fullPath: '/journey/password'
      preLoaderRoute: typeof JourneyPasswordRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/night': {
      id: '/journey/night'
      path: '/night'
      fullPath: '/journey/night'
      preLoaderRoute: typeof JourneyNightRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/music': {
      id: '/journey/music'
      path: '/music'
      fullPath: '/journey/music'
      preLoaderRoute: typeof JourneyMusicRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/memories': {
      id: '/journey/memories'
      path: '/memories'
      fullPath: '/journey/memories'
      preLoaderRoute: typeof JourneyMemoriesRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/loading': {
      id: '/journey/loading'
      path: '/loading'
      fullPath: '/journey/loading'
      preLoaderRoute: typeof JourneyLoadingRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/letter': {
      id: '/journey/letter'
      path: '/letter'
      fullPath: '/journey/letter'
      preLoaderRoute: typeof JourneyLetterRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/gift': {
      id: '/journey/gift'
      path: '/gift'
      fullPath: '/journey/gift'
      preLoaderRoute: typeof JourneyGiftRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/final': {
      id: '/journey/final'
      path: '/final'
      fullPath: '/journey/final'
      preLoaderRoute: typeof JourneyFinalRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/envelope': {
      id: '/journey/envelope'
      path: '/envelope'
      fullPath: '/journey/envelope'
      preLoaderRoute: typeof JourneyEnvelopeRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/credits': {
      id: '/journey/credits'
      path: '/credits'
      fullPath: '/journey/credits'
      preLoaderRoute: typeof JourneyCreditsRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/cake': {
      id: '/journey/cake'
      path: '/cake'
      fullPath: '/journey/cake'
      preLoaderRoute: typeof JourneyCakeRouteImport
      parentRoute: typeof JourneyRoute
    }
  }
}

interface JourneyRouteChildren {
  JourneyCakeRoute: typeof JourneyCakeRoute
  JourneyCreditsRoute: typeof JourneyCreditsRoute
  JourneyEnvelopeRoute: typeof JourneyEnvelopeRoute
  JourneyFinalRoute: typeof JourneyFinalRoute
  JourneyGiftRoute: typeof JourneyGiftRoute
  JourneyLetterRoute: typeof JourneyLetterRoute
  JourneyLoadingRoute: typeof JourneyLoadingRoute
  JourneyMemoriesRoute: typeof JourneyMemoriesRoute
  JourneyMusicRoute: typeof JourneyMusicRoute
  JourneyNightRoute: typeof JourneyNightRoute
  JourneyPasswordRoute: typeof JourneyPasswordRoute
  JourneyWishesRoute: typeof JourneyWishesRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyCakeRoute: JourneyCakeRoute,
  JourneyCreditsRoute: JourneyCreditsRoute,
  JourneyEnvelopeRoute: JourneyEnvelopeRoute,
  JourneyFinalRoute: JourneyFinalRoute,
  JourneyGiftRoute: JourneyGiftRoute,
  JourneyLetterRoute: JourneyLetterRoute,
  JourneyLoadingRoute: JourneyLoadingRoute,
  JourneyMemoriesRoute: JourneyMemoriesRoute,
  JourneyMusicRoute: JourneyMusicRoute,
  JourneyNightRoute: JourneyNightRoute,
  JourneyPasswordRoute: JourneyPasswordRoute,
  JourneyWishesRoute: JourneyWishesRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JourneyRoute: JourneyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
